version: "3.4"

networks:
  dev:
    driver: bridge

services:
  events-app:
    image: localhost/events-api:latest
    depends_on:
      - "events_db"
    container_name: event-services
    ports:
      - "8088:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres; Password=postgres; Server=events_db; Port=5432; Database=EventsDB; IntegratedSecurity=true; Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev

  events_db:
    image: postgres:latest
    container_name: events_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=EventsDB
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data: